# 醉夢描圖圖案烘焙器：twemoji_export.json → DreamTraceMotifData.h（自動生成、勿手改）
# 資料域：座標=cm（線長 108cm 域＝60s×v_max 1.8 的名義長）；runtime 依實際
# PerimeterCm 等比縮放。管線全史見 trace_motif_pipeline.py 與 SPEC v4.0a。
import json
import os
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(BASE, sys.argv[1] if len(sys.argv) > 1 else "twemoji_export.json")
OUT = os.path.normpath(os.path.join(BASE, "..", "..", "..", "Source", "NiceInk", "Private", "DreamTraceMotifData.h"))

with open(SRC, encoding="utf-8") as f:
    motifs = json.load(f)

lines = []
lines.append("// AUTO-GENERATED by Tools/AssetPrep/TraceMotifs/bake_trace_motifs.py — DO NOT EDIT")
lines.append("// 圖源＝Twemoji（CC BY 4.0）＋Wikimedia Origami Crane（CC BY-SA 3.0）；")
lines.append("// 授權明細=SourceAssets/Twemoji/ATTRIBUTION.txt——信用名單必列")
lines.append("// 座標域＝cm@108cm 線長；runtime 依 PerimeterCm 等比縮放（DreamTrace.cpp）")
lines.append("#pragma once")
lines.append("")
lines.append("#include \"CoreMinimal.h\"")
lines.append("")
lines.append("struct FDreamTraceBakedMotif")
lines.append("{")
lines.append("\tconst TCHAR* Name;")
lines.append("\tbool bClosed;")
lines.append("\tbool bMirrorAllowed;")
lines.append("\tint32 NumPoints;")
lines.append("\tconst float* Points; // x,y 交錯")
lines.append("};")
lines.append("")
lines.append("namespace NiceInkTraceMotifs")
lines.append("{")

for m in motifs:
    pts = m["points"]
    flat = []
    for x, y in pts:
        flat.append(f"{x:.3f}f")
        flat.append(f"{y:.3f}f")
    rows = [", ".join(flat[i:i + 12]) for i in range(0, len(flat), 12)]
    lines.append(f"\t// {m['name']}: {'closed' if m['closed'] else 'open'} src={m['src']} "
                 f"msd={m['msd']} dev={m['dev']} feats={m['feats']}")
    lines.append(f"\tinline constexpr float Pts_{m['name']}[] = {{")
    for r in rows:
        lines.append(f"\t\t{r},")
    lines[-1] = lines[-1].rstrip(",") if lines[-1].endswith(",,") else lines[-1]
    lines.append("\t};")
    lines.append("")

lines.append("\tinline const FDreamTraceBakedMotif Table[] =")
lines.append("\t{")
for m in motifs:
    lines.append(f"\t\t{{ TEXT(\"{m['name']}\"), {'true' if m['closed'] else 'false'}, "
                 f"{'true' if m['mirror'] else 'false'}, {len(m['points'])}, Pts_{m['name']} }},")
lines.append("\t};")
lines.append("")
lines.append(f"\tinline constexpr int32 Num = {len(motifs)};")
lines.append("")
lines.append("\t// 名字索引（DefaultParamsForCup 的池組裝用；順序=Table 順序）")
lines.append("\tenum EIdx : int32")
lines.append("\t{")
for i, m in enumerate(motifs):
    lines.append(f"\t\tIdx_{m['name']} = {i},")
lines.append("\t};")
lines.append("}")
lines.append("")

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print(f"baked {len(motifs)} motifs -> {OUT}")
for m in motifs:
    print(f"  {m['name']:10s} {'C' if m['closed'] else 'O'} pts={len(m['points'])} src={m['src']}")
