#pragma once
// GENERATED by Tools/AssetPrep/keycap_texture.py — 不要手改；改了烘焙腳本再跑一次。
// 一顆鍵一張貼圖（/Game/UI/Keys/T_Key_<KEY>；不可按＝同圖 × NiUi::KeycapDimAlpha），字烘在圖裡＝上下左右留白
// 由構造保證對稱（§15.13 十修）。BoxW／BoxH＝設計單位（1080p px）＝Slate 端 SBox 的大小、
// 也是 canvas 端 ×UiScale 的畫布大小；U1＝貼圖右邊補到 2 的冪，畫的時候 UV 只取 [0,U1]。
#include "CoreMinimal.h"

namespace NiKeycapData
{
	struct FEntry
	{
		const TCHAR* Key;
		float BoxW;
		float BoxH;
		float U1;      // 帽在貼圖上佔的寬度比例
	};
	constexpr float TexPerUnit = 5.333333f;
	constexpr float CapInset = 1.000f;    // 盒邊到帽體（投影的空間）
	constexpr FEntry Entries[] =
	{
		{ TEXT("C"), 24.0000f, 24.0000f, 1.000000f },   // 貼圖 128x128、墨跡 10.0x13.1
		{ TEXT("E"), 24.0000f, 24.0000f, 1.000000f },   // 貼圖 128x128、墨跡 7.5x12.8
		{ TEXT("F"), 24.0000f, 24.0000f, 1.000000f },   // 貼圖 128x128、墨跡 7.5x12.8
		{ TEXT("G"), 24.0000f, 24.0000f, 1.000000f },   // 貼圖 128x128、墨跡 10.6x13.1
		{ TEXT("L"), 24.0000f, 24.0000f, 1.000000f },   // 貼圖 128x128、墨跡 8.1x12.8
		{ TEXT("Q"), 24.0000f, 24.0000f, 1.000000f },   // 貼圖 128x128、墨跡 12.2x15.9
		{ TEXT("ESC"), 42.5625f, 24.0000f, 0.886719f },   // 貼圖 256x128、墨跡 28.7x13.1
		{ TEXT("ENTER"), 67.6875f, 24.0000f, 0.705078f },   // 貼圖 512x128、墨跡 53.7x12.8
		{ TEXT("SHIFT"), 62.2500f, 24.0000f, 0.648438f },   // 貼圖 512x128、墨跡 48.4x13.1
		{ TEXT("TAB"), 46.6875f, 24.0000f, 0.972656f },   // 貼圖 256x128、墨跡 32.7x12.8
		{ TEXT("WASD"), 64.5000f, 24.0000f, 0.671875f },   // 貼圖 512x128、墨跡 50.5x13.1
		{ TEXT("SCROLL"), 78.1875f, 24.0000f, 0.814453f },   // 貼圖 512x128、墨跡 64.2x13.2
	};
	constexpr int32 Num = 12;

	/** 表查找；沒有＝nullptr（呼叫端退回 9-slice＋Slate 排字）。 */
	inline const FEntry* Find(const FString& Key)
	{
		for (const FEntry& E : Entries)
		{
			if (Key.Equals(E.Key, ESearchCase::CaseSensitive)) { return &E; }
		}
		return nullptr;
	}
}
