# DrawPoseData.h 生成器：drawpose_ue_dump.json（UE 空間每骨 local transform、雙姿勢）→ C++ 標頭
#
# 管線全貌（直接畫制的姿勢搬運路徑，v3.8 軸向重映射鐵坑的安全解）：
#   1. Tools/AssetPrep/export_drawpose_fbx.py（Blender：套姿勢→骨架單幀動畫 FBX；
#      預設=base20 DrawPose_Backup2 坐姿；lean 端點用 `-- <blend> <action> <out>` 參數）
#   2. scratchpad ue_import_dump_both.py（UE headless：兩支 FBX → A_SumoDrawPose /
#      A_SumoDrawPoseLean → AnimationLibrary 讀 local transform → JSON；
#      需 -EnablePlugins=AnimationData）
#   3. 本腳本（JSON → Source/NiceInk/Private/DrawPoseData.h：SitBones + LeanBones）
#
# 單位鐵坑（robo 實錘）：FBX 骨架節點 scale=100 以「節點根骨 scale=100」烘在引擎
# RefSkeleton；骨軌位移是公尺域原生值，CS 組合時由根骨 scale 放大成公分——
# 生成器不得再 x100（雙重縮放=2174cm 髖高）。
#
# Run: python gen_drawpose_header.py
import json, math
from pathlib import Path

SRC = Path(r"C:/games/Unreal Engine/nice_ink/Saved/drawpose_ue_dump.json")
DST = Path(r"C:/games/Unreal Engine/nice_ink/Source/NiceInk/Private/DrawPoseData.h")

BONE_SET = {
    "Root", "Hips", "Spine", "Spine1", "Neck", "Head",
    "LeftShoulder", "LeftArm", "LeftForeArm", "LeftHand",
    "LeftHandIndex1", "LeftHandIndex2", "LeftHandThumb1", "LeftHandThumb2", "LeftHandProp",
    "RightShoulder", "RightArm", "RightForeArm", "RightHand",
    "RightHandIndex1", "RightHandIndex2", "RightHandThumb1", "RightHandThumb2", "RightHandProp",
    "LeftUpLeg", "LeftLeg", "LeftFoot", "LeftToeBase",
    "RightUpLeg", "RightLeg", "RightFoot", "RightToeBase",
    "Jiggle_Belly", "Jiggle_Chest_L", "Jiggle_Chest_R", "Jiggle_Butt_L", "Jiggle_Butt_R",
}
CANON = {n.lower(): n for n in BONE_SET}

data = json.loads(SRC.read_text(encoding="utf-8"))


def extract(seq_key):
    seq = data[seq_key]
    rows = []
    for raw_name in seq["order"]:
        name = CANON.get(raw_name.lower())
        b = seq["bones"][raw_name]
        if name is None:
            assert all(abs(s - 100.0) < 0.5 for s in b["scale"]), \
                f"non-bone track {raw_name} unexpected scale {b['scale']} (unit carrier must be 100)"
            continue
        lx, ly, lz = b["loc"]
        qx, qy, qz, qw = b["quat"]
        n = math.sqrt(qx*qx + qy*qy + qz*qz + qw*qw)
        assert n > 0.5, f"degenerate quat on {name}"
        qx, qy, qz, qw = qx/n, qy/n, qz/n, qw/n
        assert all(abs(s - 1.0) < 0.01 for s in b["scale"]), f"non-unit scale on {name}: {b['scale']}"
        rows.append((name, lx, ly, lz, qx, qy, qz, qw))
    assert len(rows) == 37, f"{seq_key}: expected 37 bone tracks, got {len(rows)}"
    return rows


sit = extract("A_SumoDrawPose")
lean = extract("A_SumoDrawPoseLean")
assert [r[0] for r in sit] == [r[0] for r in lean], "sit/lean bone order mismatch"


def emit(rows, sym):
    out = [f"inline const FBonePose {sym}[NumBones] = {{"]
    for (name, lx, ly, lz, qx, qy, qz, qw) in rows:
        out.append(
            f"\t{{ TEXT(\"{name}\"), "
            f"{lx:.8f}f, {ly:.8f}f, {lz:.8f}f, "
            f"{qx:.8f}f, {qy:.8f}f, {qz:.8f}f, {qw:.8f}f }},")
    out.append("};")
    return out


lines = []
lines.append("// GENERATED by Tools/AssetPrep/gen_drawpose_header.py -- do not hand-edit.")
lines.append("// Source: sumo_retopo_base20.blend, user 手擺雙端點：")
lines.append("//   SitBones  = DrawPose_Backup2（盤腿坐直、作畫基底）")
lines.append("//   LeanBones = DrawPose_Backup4（前傾極限——核心很強的前傾）")
lines.append("// 直接畫制解算＝兩端點逐骨插值 t（程式不發明姿勢）＋Neck 殘差對準臉向。")
lines.append("// 座標語義：每骨 parent-space local transform（UE 慣例），Root 在陣列首。")
lines.append("// 單位：骨軌原生單位（公尺域）——RefSkeleton 節點根骨 scale=100 於 CS 組合時")
lines.append("// 放大成公分（不得再 x100：雙重縮放=2174cm 髖高，robo 實錘）。")
lines.append("#pragma once")
lines.append("")
lines.append("#include \"CoreMinimal.h\"")
lines.append("")
lines.append("namespace DrawPoseData")
lines.append("{")
lines.append("struct FBonePose")
lines.append("{")
lines.append("\tconst TCHAR* Name;")
lines.append("\tfloat LX, LY, LZ;      // parent-space translation (native units, see header note)")
lines.append("\tfloat QX, QY, QZ, QW;  // parent-space rotation quaternion")
lines.append("};")
lines.append("")
lines.append(f"inline constexpr int32 NumBones = {len(sit)};")
lines.append("")
lines.extend(emit(sit, "SitBones"))
lines.append("")
lines.extend(emit(lean, "LeanBones"))
lines.append("}  // namespace DrawPoseData")
lines.append("")

DST.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"WROTE {DST} (37 bones x2 poses)")
