# NeckOuterData.h 生成（2026-08-16 短脖頸皮）：從 neck_outer_rings.json 產 UE 常數表。
# 座標約定同 NeckSeamData：UE component space = (x, -y, z) × 100。
import json
SRC = r"C:/games/Unreal Engine/nice_ink/SourceAssets/neck_outer_rings.json"
OUT = r"C:/games/Unreal Engine/nice_ink/Source/NiceInk/Private/NeckOuterData.h"
d = json.load(open(SRC, encoding="utf-8"))
S = d["steps"]; N = d["count"]
L = []
L.append("// NeckOuterData.h — GENERATED by Tools/AssetPrep/sumo_neck_outer_header.py. DO NOT EDIT.")
L.append("// 短脖程序化頸皮原料：seam 兩側各 OuterSteps 圈外環（沿 seam 平面法線逐邊外走），")
L.append("// 每環與 seam 環逐點對應（k 同索引）。UE component space cm；法線=rest 頂點法線。")
L.append("#pragma once")
L.append("#include \"CoreMinimal.h\"")
L.append("")
L.append("namespace NeckOuterData")
L.append("{")
L.append(f"constexpr int32 OuterSteps = {S};")
L.append(f"constexpr int32 RingCount = {N};")
L.append("struct FOuterVert { float Px, Py, Pz; float Nx, Ny, Nz; };")
def emit(name, rows):
    L.append(f"// {name}[step][k]")
    L.append(f"constexpr FOuterVert {name}[OuterSteps][RingCount] = {{")
    for s in range(S):
        L.append("\t{")
        for k in range(N):
            v = rows[k][s]; p = v["pos"]; n = v["nrm"]
            L.append(f"\t\t{{{p[0]*100:.4f}f,{-p[1]*100:.4f}f,{p[2]*100:.4f}f, {n[0]:.5f}f,{-n[1]:.5f}f,{n[2]:.5f}f}},")
        L.append("\t},")
    L.append("};")
emit("HeadOuter", d["head_out"])
emit("BodyOuter", d["body_out"])
L.append("}")
L.append("")
open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
print("HEADER ->", OUT)
